apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: benchmark-workers
    app.kubernetes.io/component: workers
  name: benchmark-workers
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: benchmark-workers
      app.kubernetes.io/component: workers
  template:
    metadata:
      labels:
        app.kubernetes.io/name: benchmark-workers
        app.kubernetes.io/component: workers
    spec:
      initContainers:
        - name: create-namespace
          image: temporalio/admin-tools:1.18.0
          env:
          - name: TEMPORAL_CLI_ADDRESS
            value: "temporal-frontend:7233"
          command: ["bash", "-c"]
          args: ["tctl --namespace default namespace register || tctl --namespace default namespace describe"]
      containers:
      - image: ghcr.io/temporalio/benchmark-workers:main
        imagePullPolicy: Always
        name: benchmark-workers
        env:
        - name: TEMPORAL_GRPC_ENDPOINT
          value: "temporal-frontend:7233"
        - name: PROMETHEUS_ENDPOINT
          value: 0.0.0.0:8000
        - name: TEMPORAL_NAMESPACE
          value: "default"
        - name: TEMPORAL_TASK_QUEUE
          value: "benchmark"
        - name: TEMPORAL_WORKFLOW_TASK_POLLERS
          value: "256"
        - name: TEMPORAL_ACTIVITY_TASK_POLLERS
          value: "128"
        ports:
        - name: metrics
          containerPort: 8000
          protocol: TCP
      restartPolicy: Always